-- Initial schema for both independent domains this project exposes behind
-- one GraphQL schema. Flyway owns the schema, Hibernate only validates
-- against it (ddl-auto: validate), so every table, constraint and index the
-- JPA entities rely on must exist here.
--
-- The identity/RBAC domain (users, roles, permissions and their join
-- tables, plus the token tables) and the e-commerce domain (categories,
-- products, customers, orders) share this database but have no foreign key
-- between them. A customer never resolves to a user at the data level.

-- Identity/RBAC domain

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100)  NOT NULL,
    last_name       VARCHAR(100)  NOT NULL,
    email           VARCHAR(255)  NOT NULL UNIQUE,
    password        VARCHAR(255)  NOT NULL,
    enabled         BOOLEAN       NOT NULL DEFAULT FALSE,
    account_locked  BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE permissions
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource  VARCHAR(100) NOT NULL,
    action    VARCHAR(50)  NOT NULL,
    UNIQUE (resource, action)
);

CREATE TABLE role_user
(
    role_id  BIGINT NOT NULL REFERENCES roles (id),
    user_id  BIGINT NOT NULL REFERENCES users (id),
    PRIMARY KEY (role_id, user_id)
);

CREATE INDEX idx_role_user_user_id ON role_user (user_id);

CREATE TABLE role_permission
(
    role_id        BIGINT NOT NULL REFERENCES roles (id),
    permission_id  BIGINT NOT NULL REFERENCES permissions (id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX idx_role_permission_permission_id ON role_permission (permission_id);

CREATE TABLE activation_tokens
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users (id),
    token         VARCHAR(255) NOT NULL UNIQUE,
    created_at    TIMESTAMP    NOT NULL,
    expires_at    TIMESTAMP    NOT NULL,
    validated_at  TIMESTAMP
);

CREATE INDEX idx_activation_tokens_user_id ON activation_tokens (user_id);

CREATE TABLE blacklisted_tokens
(
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id),
    token           VARCHAR(500) NOT NULL,
    jti             VARCHAR(255) NOT NULL UNIQUE,
    blacklisted_at  TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    expires_at      TIMESTAMP    NOT NULL,
    validated_at    TIMESTAMP
);

CREATE INDEX idx_blacklisted_tokens_user_id ON blacklisted_tokens (user_id);

CREATE TABLE password_reset_tokens
(
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id),
    token        VARCHAR(255) NOT NULL UNIQUE,
    type         VARCHAR(50)  NOT NULL,
    expiry_date  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

-- E-commerce domain

CREATE TABLE categories
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE products
(
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   BIGINT         NOT NULL REFERENCES categories (id),
    product_name  VARCHAR(150)   NOT NULL,
    unit_price    NUMERIC(10, 2) NOT NULL CHECK (unit_price > 0)
);

CREATE INDEX idx_products_category_id ON products (category_id);

CREATE TABLE customers
(
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    telephone   VARCHAR(30)  NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    address     VARCHAR(255) NOT NULL
);

CREATE TABLE orders
(
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT         NOT NULL REFERENCES customers (id),
    product_id   BIGINT         NOT NULL REFERENCES products (id),
    quantity     INTEGER        NOT NULL CHECK (quantity > 0),
    total        NUMERIC(12, 2) NOT NULL CHECK (total > 0)
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_product_id ON orders (product_id);
